<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>BlockPlayerStatusReport</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>./lib/BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>./lib/BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="HarmonyLib">
      <HintPath>./lib/HarmonyLib.dll</HintPath>
    </Reference>
    <Reference Include="GTFO.API">
      <HintPath>./lib/GTFO‑API.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Plugin.cs"/>
  </ItemGroup>
</Project>
